

# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua


$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = hyprlauncher

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu

monitor=eDP-1,1920x1080@60,0x0,1

general {
    gaps_in = 6
    gaps_out = 12
    border_size = 2
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.active_border = rgba(595959aa)
  }

decoration {
    rounding = 10
    active_opacity = 1.0
    inactive_opacity = 0.9
  }
