#!/usr/bin/env sh

# Kachel-Layout aktivieren
yabai -m config layout bsp

# Abstände (Gaps) zwischen den Fenstern
yabai -m config window_gap 10
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10

echo "yabai configuration loaded.."
