#!/usr/bin/env sh

yabai -m config layout bsp

yabai -m config window_gap 10
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10

echo "yabai configuration loaded.."

# --- (Floating Windows) ---
yabai -m rule --add app="^Systemeinstellungen$" manage=off grid=4:4:1:1:2:2
yabai -m rule --add app="^System Settings$" manage=off grid=4:4:1:1:2:2
yabai -m rule --add app="^Rechner$" manage=off grid=4:4:1:1:2:2
yabai -m rule --add app="^Calculator$" manage=off grid=4:4:1:1:2:2
