# 1. Wahre Farben (True Color) aktivieren
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# 2. Das grauenhafte Strg+b deaktivieren und auf Strg+Leertaste ändern
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# 3. Maus-Support aktivieren (nur für den Notfall, z.B. Scrollen)
set -g mouse on

# 4. Plugins laden (Der Plugin Manager MUSS ganz oben in der Liste stehen)
set -g @plugin 'tmux-plugins/tpm'

# 5. Deine Magische Brücke zu Neovim
set -g @plugin 'christoomey/vim-tmux-navigator'

# 6. Das TokyoNight Theme (damit die grüne Leiste verschwindet!)
set -g @plugin 'theutz/tmux-tokyonight-nvim'

# TPM Initialisieren (MUSS GANZ UNTEN STEHEN)
run '~/.tmux/plugins/tpm/tpm'
